// Strip variation selectors & zero-width joiners so object-key lookups work
export const norm = (s) => s.replace(/[\uFE0E\uFE0F\u200D]/g, "");

// ─── Categories ─────────────────────────────────────────────────────────────
export const EMOJI_CATEGORIES = [
  {
    label: "😀",
    name: "Smileys",
    emojis: [
      "😀","😃","😄","😁","😆","😅","🤣","😂","🙂","🙃",
      "😉","😊","😇","🥰","😍","🤩","😘","😗","☺️","😚",
      "😙","🥲","😋","😛","😜","🤪","😝","🤑","🤗","🤭",
      "🤫","🤔","🤐","🤨","😐","😑","😶","😏","😣","😥",
      "😮","🤯","😳","🥺","😦","😧","😨","😰","😩",
      "😢","😭","😱","😖","😡","🤬","😤","😈",
      "👿","💀","☠️","💩","🤡","👹","👺","👻","👽","🤖",
    ],
  },
  {
    label: "👋",
    name: "People",
    emojis: [
      "👋","🤚","🖐️","✋","🖖","👌","🤌","🤏","✌️","🤞",
      "🤟","🤘","🤙","👈","👉","👆","🖕","👇","☝️","👍",
      "👎","✊","👊","🤛","🤜","👏","🙌","👐","🤲","🤝",
      "🙏","✍️","💅","🤳","💪","🦾","🦿","🦵","🦶","👂",
      "🦻","👃","🧠","🫀","🫁","🦷","🦴","👀","👁️","👅",
      "👄","🫂","👶","🧒","👦","👧","🧑","👱","👨","🧔",
      "👩","🧓","👴","👵",
    ],
  },
  {
    label: "❤️",
    name: "Hearts",
    emojis: [
      "❤️","🧡","💛","💚","💙","💜","🖤","🤍","🤎","💔",
      "❣️","💕","💞","💓","💗","💖","💘","💝","💟","☮️",
      "✝️","☪️","🕉️","☸️","✡️","🔯","🕎","☯️","☦️","🛐",
    ],
  },
  {
    label: "🐶",
    name: "Animals",
    emojis: [
      "🐶","🐱","🐭","🐹","🐰","🦊","🐻","🐼","🐻‍❄️","🐨",
      "🐯","🦁","🐮","🐷","🐽","🐸","🐵","🙈","🙉","🙊",
      "🐒","🐔","🐧","🐦","🐤","🐣","🐥","🦆","🦅","🦉",
      "🦇","🐺","🐗","🐴","🦄","🐝","🪲","🐛","🦋","🐌",
      "🐞","🐜","🪰","🪳","🕷️","🦂","🐢","🐍","🦎","🦖",
      "🦕","🐙","🦑","🦐","🦞","🦀","🐠","🐟","🐡","🐬",
      "🐳","🐋","🦈","🐊","🐆","🐅","🐃","🐂","🐄","🦬",
      "🦣","🦏","🦛","🐘","🦒","🦘","🦫","🦦","🦥","🐁",
      "🐀","🐿️","🦔","🐾","🐉","🐲","🌵","🎄","🌲","🌳",
    ],
  },
  {
    label: "🍎",
    name: "Food",
    emojis: [
      "🍎","🍐","🍊","🍋","🍌","🍉","🍇","🍓","🫐","🍈",
      "🍒","🍑","🥭","🍍","🥥","🥝","🍅","🍆","🥑","🍦",
      "🍧","🍨","🍩","🍪","🎂","🍰","🧁","🥧","🍫","🍬",
      "🍭","🍮","🍯","🧂","🥫","🍿","🧈","🥚","🍳","🥞",
      "🧇","🥓","🥩","🍗","🍖","🌭","🍔","🍟","🍕","🫓",
      "🌮","🌯","🫔","🥙","🧆","🍲","🥘","🍛","🍜",
      "🍝","🍠","🍢","🍣","🍤","🍥","🥮","🍡","🥟","🥠",
      "🥡","🍱","🍘","🍙","🍚","🥣","🥗","🧃",
      "🥤","🧋","☕","🍵","🫖","🧉","🍶","🍾","🍷","🍸",
      "🍹","🍺","🍻","🥂","🥃","🫗",
    ],
  },
  {
    label: "⚽",
    name: "Sports",
    emojis: [
      "⚽","🏀","🏈","⚾","🥎","🎾","🏐","🏉","🥏","🎱",
      "🏓","🏸","🏒","🏑","🥍","🏏","🪃","🥅","⛳","🪁",
      "🏹","🎣","🤿","🥊","🥋","🎽","🛹","🛼","🛷","⛸️",
      "🥌","🎿","🏂","🏋️","🤼","🤸","⛹️","🤺","🏇","🧘",
      "🏄","🏊","🤽","🚣","🧗","🚴","🚵","🎖️","🏆","🏅",
      "🥇","🥈","🥉",
    ],
  },
  {
    label: "🚗",
    name: "Travel",
    emojis: [
      "🚗","🚕","🚙","🛻","🚌","🚎","🏎️","🚓","🚑","🚒",
      "🚐","🛵","🦽","🦼","🛺","🚲","🛴","🛹","🛼","🚏",
      "🛣️","🛤️","🛞","⛽","🚨","🚥","🚦","🛑","⛵","🛶",
      "🚤","🛳️","⛴️","🛥️","🚢","✈️","🛩️","🛫","🛬","🪂",
      "💺","🚁","🚟","🚠","🚡","🛸","🚀","🛰️","🧳","🌍",
      "🌎","🌏","🗺️","🏔️","⛰️","🌋","🗻","🏕️","🏖️","🏜️",
      "🏝️","🏞️","🏟️","🏛️","🏗️","🧱","🪨","🪵","🛖","🏘️",
      "🏚️","🏠","🏡","🏢","🏣","🏤","🏥","🏦","🏨","🏩",
      "🏪","🏫","🏬","🏭","🏯","🏰","💒","🗼","🗽","⛪",
    ],
  },
  {
    label: "💡",
    name: "Objects",
    emojis: [
      "💡","🔦","🕯️","🪔","🧯","🛢️","💈","⚗️","🔭","🔬",
      "🩺","🩹","🩼","💊","💉","🩸","🔧","🪛","🔩",
      "⚙️","🗜️","⚖️","🦯","🔗","⛓️","🪝","🧰","🪤","🧲",
      "🪜","🧪","🧫","🧬","📡",
      "📱","💻","🖥️","🖨️","⌨️","🖱️","🖲️","💽","💾","💿",
      "📀","📼","📷","📸","📹","🎥","📽️","🎞️","📞","☎️",
      "📟","📠","📺","📻","🧭","⏱️","⏲️","⏰","⏳","⌛",
      "🔋","🪫","🔌","🗑️",
      "🛒","🎁","🎈","🎀","🎊","🎉","🎎","🎏","🎐","🧧",
      "📦","📮","📫","📪","📬","📭","📧","📨","📩","📤",
    ],
  },
  {
    label: "⭐",
    name: "Symbols",
    emojis: [
      "⭐","🌟","✨","💫","⚡","🌈","☀️","🌤️","⛅","🌥️",
      "☁️","🌦️","🌧️","⛈️","🌩️","🌨️","❄️","☃️","⛄","🌬️",
      "💨","💧","💦","☔","☂️","🌊","🌪️","🔥","🌡️",
      "🌙","🌛","🌜","🌝","🌞","🪐",
      "☄️","🌍","🌎","🌏","🗺️","🧭","🏔️","⛰️","🌋",
      "♈","♉","♊","♋","♌","♍","♎","♏","♐","♑",
      "♒","♓","⛎","🔀","🔁","🔂","▶️","⏩","⏭️","⏯️",
      "◀️","⏪","⏮️","🔼","⏫","🔽","⏬","⏸️","⏹️","⏺️",
      "⏏️","🎵","🎶","🔇","🔈","🔉","🔊","📢","📣","📯",
      "🔔","🔕","✅","☑️","✔️","❌","❎","➕","➖","➗",
      "✖️","♾️","💲","💱","🔱","📛","🔰","⭕",
      "❓","❔","❗","❕","🆚","💮","🉐","㊙️","㊗️","🈴",
    ],
  },
  {
    label: "🔤",
    name: "Flags",
    emojis: [
      "🏳️","🏴","🚩","🎌","🏁","🏳️‍🌈","🏳️‍⚧️","🏴‍☠️",
    ],
  },
];

// ─── Keywords ───────────────────────────────────────────────────────────────
export const EMOJI_KEYWORDS = {
  "😀":"grinning face","😃":"big grin smile","😄":"grinning big eyes","😁":"beaming face smile","😆":"laughing grinning","😅":"sweat smile","🤣":"rolling laughing","😂":"joy crying laugh","🙂":"slightly smiling","🙃":"upside down smile",
  "😉":"wink winking","😊":"smiling closed eyes","😇":"angel halo","🥰":"heart eyes love","😍":"star eyes love","🤩":"star struck","😘":"kiss mark","😗":"kissing face","☺️":"smiling face","😚":"kissing closed eyes",
  "😙":"kissing smile","🥲":"tear joy","😋":"face savoring","😛":"tongue out","😜":"winking tongue","🤪":"zany crazy face","😝":"stuck out tongue","🤑":"money mouth","🤗":"hugging face","🤭":"hand over mouth",
  "🤫":"shushing face quiet","🤔":"thinking face","🤐":"zipper mouth","🤨":"raised eyebrow","😐":"neutral face","😑":"expressionless","😶":"no mouth","😏":"smirking","😣":"persevere anguish","😥":"disappointed relieved sad",
  "😮":"open mouth","🤯":"exploding head mind blown","😳":"flushed face","🥺":"pleading face","😦":"frowning","😧":"anguished","😨":"fearful scared","😰":"anxious sweat","😩":"weary tired","😢":"crying sad",
  "😭":"loudly crying","😱":"face screaming","😖":"confounded","😡":"angry pouting","🤬":"swearing cursing","😤":"huffing triumph","😈":"smiling devil evil","👿":"angry devil","💀":"skull dead","☠️":"skull crossbones",
  "💩":"pile of poo","🤡":"clown face","👹":"goblin monster","👺":"japanese ogre","👻":"ghost","👽":"alien","🤖":"robot",
  "👋":"waving hand hello","🤚":"raised back hand","🖐️":"raised hand fingers splayed","✋":"raised hand stop","🖖":"vulcan salute","👌":"ok hand","🤌":"pinched fingers","🤏":"pinching hand","✌️":"victory hand peace","🤞":"crossed fingers luck",
  "🤟":"love you hand","🤘":"sign horns rock","🤙":"call me hand","👈":"point left","👉":"point right","👆":"point up","🖕":"middle finger","👇":"point down","☝️":"index pointing up","👍":"thumbs up good",
  "👎":"thumbs down bad","✊":"raised fist","👊":"oncoming fist punch","🤛":"fist left","🤜":"fist right","👏":"clapping hands","🙌":"raising hands","👐":"open hands","🤲":"palms up","🤝":"handshake",
  "🙏":"folded hands pray","✍️":"writing hand","💅":"nail polish","🤳":"selfie","💪":"flexed bicep strong","🦾":"mechanical arm","🦿":"mechanical leg","🦵":"leg","🦶":"foot","👂":"ear listening",
  "🦻":"ear with hearing aid","👃":"nose smell","🧠":"brain think","🫀":"anatomical heart","🫁":"lungs","🦷":"tooth","🦴":"bone","👀":"eyes looking","👁️":"eye","👅":"tongue",
  "👄":"mouth lips","🫂":"people hugging","👶":"baby infant","🧒":"child","👦":"boy","👧":"girl","🧑":"person","👱":"person blond hair","👨":"man","🧔":"person beard",
  "👩":"woman","🧓":"older person","👴":"old man","👵":"old woman",
  "❤️":"red heart love","🧡":"orange heart","💛":"yellow heart","💚":"green heart","💙":"blue heart","💜":"purple heart","🖤":"black heart","🤍":"white heart","🤎":"brown heart","💔":"broken heart",
  "❣️":"heart exclamation","💕":"two hearts","💞":"revolving hearts","💓":"growing heart","💗":"sparkling heart","💖":"sparkling heart","💘":"heart arrow","💝":"heart ribbon","💟":"heart decoration",
  "☮️":"peace symbol","✝️":"latin cross","☪️":"star crescent","🕉️":"om","☸️":"wheel dharma","✡️":"star david","🔯":"six pointed star","🕎":"menorah","☯️":"yin yang","☦️":"orthodox cross","🛐":"religion",
  "🐶":"dog face woof","🐱":"cat face meow","🐭":"mouse face","🐹":"hamster face","🐰":"rabbit face","🦊":"fox face","🐻":"bear face","🐼":"panda face","🐻‍❄️":"polar bear","🐨":"koala",
  "🐯":"tiger face","🦁":"lion face king","🐮":"cow face","🐷":"pig face","🐽":"pig nose","🐸":"frog face","🐵":"monkey face","🙈":"see no evil","🙉":"hear no evil","🙊":"speak no evil",
  "🐒":"monkey","🐔":"chicken","🐧":"penguin","🐦":"bird","🐤":"baby chick","🐣":"hatching chick","🐥":"hatched chick","🦆":"duck","🦅":"eagle","🦉":"owl",
  "🦇":"bat","🐺":"wolf","🐗":"boar","🐴":"horse face","🦄":"unicorn","🐝":"honeybee","🪲":"beetle","🐛":"bug worm","🦋":"butterfly","🐌":"snail",
  "🐞":"ladybug","🐜":"ant","🪰":"fly","🪳":"cockroach","🕷️":"spider","🦂":"scorpion","🐢":"turtle","🐍":"snake","🦎":"lizard","🦖":"sauropod dinosaur",
  "🦕":"t-rex dinosaur","🐙":"octopus","🦑":"squid","🦐":"shrimp","🦞":"lobster","🦀":"crab","🐠":"tropical fish","🐟":"fish","🐡":"blowfish","🐬":"dolphin",
  "🐳":"whale","🐋":"whale","🦈":"shark","🐊":"crocodile","🐆":"leopard","🐅":"tiger","🐃":"water buffalo","🐂":"ox","🐄":"cow","🦬":"bison",
  "🦣":"mammoth","🦏":"rhinoceros","🦛":"hippopotamus","🐘":"elephant","🦒":"giraffe","🦘":"kangaroo","🦫":"beaver","🦦":"otter","🦥":"sloth","🐁":"mouse",
  "🐀":"rat","🐿️":"chipmunk","🦔":"hedgehog","🐾":"paw prints","🐉":"dragon","🐲":"dragon","🌵":"cactus","🎄":"christmas tree","🌲":"evergreen tree","🌳":"deciduous tree",
  "🍎":"red apple fruit","🍐":"pear fruit","🍊":"tangerine orange fruit","🍋":"lemon fruit","🍌":"banana fruit","🍉":"watermelon fruit","🍇":"grapes fruit","🍓":"strawberry fruit","🫐":"blueberries fruit","🍈":"melon fruit",
  "🍒":"cherries fruit","🍑":"peach fruit","🥭":"mango fruit","🍍":"pineapple fruit","🥥":"coconut fruit","🥝":"kiwi fruit","🍅":"tomato","🍆":"eggplant","🥑":"avocado",
  "🍦":"soft ice cream","🍧":"shaved ice","🍨":"ice cream","🍩":"donut","🍪":"cookie","🎂":"birthday cake","🍰":"slice of cake","🧁":"cupcake","🥧":"pie","🍫":"chocolate bar",
  "🍬":"candy","🍭":"lollipop","🍮":"custard dessert","🍯":"honey pot","🧂":"salt","🥫":"canned food","🍿":"popcorn","🧈":"butter","🥚":"egg","🍳":"cooking egg",
  "🥞":"pancakes","🧇":"waffle","🥓":"bacon","🥩":"steak meat","🍗":"chicken leg","🍖":"meat on bone","🌭":"hot dog","🍔":"hamburger","🍟":"french fries","🍕":"slice of pizza",
  "🫓":"flatbread","🌮":"taco","🌯":"burrito","🫔":"tamale","🥙":"falafel pita","🧆":"falafel","🍲":"pot of food stew","🥘":"shallow pan","🍛":"curry rice","🍜":"noodles ramen",
  "🍝":"spaghetti pasta","🍠":"roasted sweet potato","🍢":"oden","🍣":"sushi","🍤":"shrimp","🍥":"fish cake","🥮":"mooncake","🍡":"dango","🥟":"dumpling","🥠":"fortune cookie",
  "🥡":"takeout box","🍱":"bento box","🍘":"rice ball","🍙":"rice cracker","🍚":"rice","🥣":"bowl with spoon cereal","🥗":"green salad","🧃":"juice box drink","🥤":"cup with straw drink","🧋":"bubble tea drink",
  "☕":"hot beverage coffee","🍵":"teacup tea","🫖":"teapot tea","🧉":"mate drink","🍶":"sake bottle","🍾":"champagne bottle","🍷":"wine glass","🍸":"cocktail glass","🍹":"tropical drink","🍺":"beer mug",
  "🍻":"clinking beer mugs","🥂":"clinking glasses champagne","🥃":"tumbler glass whiskey","🫗":"pouring liquid",
  "⚽":"soccer football","🏀":"basketball","🏈":"american football","⚾":"baseball","🥎":"softball","🎾":"tennis","🏐":"volleyball","🏉":"rugby","🥏":"flying disc","🎱":"pool billiards",
  "🏓":"table tennis ping pong","🏸":"badminton","🏒":"ice hockey","🏑":"field hockey","🥍":"lacrosse","🏏":"cricket","🪃":"boomerang","🥅":"goal net","⛳":"golf","🪁":"kite",
  "🏹":"bow arrow","🎣":"fishing pole","🤿":"diving","🥊":"boxing glove","🥋":"martial arts","🎽":"running shirt","🛹":"skateboard","🛼":"roller skate","🛷":"sled","⛸️":"ice skate",
  "🥌":"curling stone","🎿":"skis skiing","🏂":"snowboarding","🏋️":"weightlifting","🤼":"wrestling","🤸":"gymnastics","⛹️":"person bouncing ball","🤺":"fencing","🏇":"horse racing","🧘":"meditation yoga",
  "🏄":"surfing","🏊":"swimming","🤽":"water polo","🚣":"rowing boat","🧗":"climbing","🚴":"bicycling","🚵":"mountain biking","🎖️":"medal","🏆":"trophy winner","🏅":"medal sports",
  "🥇":"gold medal first","🥈":"silver medal second","🥉":"bronze medal third",
  "🚗":"red car automobile","🚕":"taxi cab","🚙":"SUV vehicle","🛻":"pickup truck","🚌":"bus","🚎":"trolleybus","🏎️":"racing car","🚓":"police car","🚑":"ambulance","🚒":"fire engine truck",
  "🚐":"minibus van","🛵":"motor scooter","🦽":"motorized wheelchair","🦼":"manual wheelchair","🛺":"auto rickshaw","🚲":"bicycle bike","🛴":"kick scooter","🚏":"bus stop",
  "🛣️":"motorway highway","🛤️":"railway track","🛞":"wheel","⛽":"fuel pump gas","🚨":"police car light","🚥":"traffic light","🚦":"traffic light","🛑":"stop sign","⛵":"sailboat","🛶":"canoe",
  "🚤":"speedboat","🛳️":"passenger ship","⛴️":"ferry","🛥️":"motor boat","🚢":"ship","✈️":"airplane plane","🛩️":"small airplane","🛫":"airplane departure","🛬":"airplane arrival","🪂":"parachute",
  "💺":"seat airplane","🚁":"helicopter","🚟":"suspended railway","🚠":"mountain railway","🚡":"monorail","🛸":"flying saucer ufo","🚀":"rocket space","🛰️":"satellite","🧳":"luggage travel",
  "🌍":"earth globe europe africa","🌎":"earth globe americas","🌏":"earth globe asia australia","🗺️":"world map","🏔️":"mountain","⛰️":"mountain","🌋":"volcano","🗻":"mount fuji","🏕️":"camping tent","🏖️":"beach umbrella","🏜️":"desert",
  "🏝️":"desert island","🏞️":"national park","🏟️":"stadium","🏛️":"classical building","🏗️":"building construction","🧱":"brick","🪨":"rock stone","🪵":"wood log","🛖":"hut","🏘️":"houses",
  "🏚️":"derelict house","🏠":"house home","🏡":"house with garden","🏢":"office building","🏣":"japanese post office","🏤":"european post office","🏥":"hospital","🏦":"bank","🏨":"hotel","🏩":"love hotel",
  "🏪":"convenience store","🏫":"school","🏬":"department store","🏭":"factory","🏯":"japanese castle","🏰":"castle","💒":"wedding church","🗼":"tokyo tower","🗽":"statue liberty","⛪":"church",
  "💡":"light bulb idea","🔦":"flashlight torch","🕯️":"candle light","🪔":"diya lamp","🧯":"fire extinguisher","🛢️":"oil drum barrel","💈":"barber pole","⚗️":"alembic","🔭":"telescope","🔬":"microscope",
  "🩺":"stethoscope medical","🩹":"adhesive bandage","🩼":"crutch","💊":"pill medicine tablet","💉":"syringe needle","🩸":"drop of blood","🔧":"wrench tool","🪛":"screwdriver tool","🔩":"nut bolt screw",
  "⚙️":"gear settings","🗜️":"clamp","⚖️":"balance scale","🦯":"white cane","🔗":"link chain","⛓️":"chains","🪝":"hook","🧰":"toolbox","🪤":"mouse trap","🧲":"magnet",
  "🪜":"ladder","🧪":"test tube","🧫":"petri dish","🧬":"dna","📡":"satellite antenna","📱":"mobile phone","💻":"laptop computer","🖥️":"desktop computer","🖨️":"printer","⌨️":"keyboard",
  "🖱️":"computer mouse","🖲️":"trackball","💽":"optical disc","💾":"floppy disk","💿":"optical disc cd","📀":"optical disc dvd","📼":"videocassette vhs","📷":"camera photo","📸":"camera flash","📹":"video camera",
  "🎥":"movie camera film","📽️":"film projector","🎞️":"film frames","📞":"telephone receiver","☎️":"telephone","📟":"pager","📠":"fax machine","📺":"television tv","📻":"radio","🧭":"compass",
  "⏱️":"stopwatch","⏲️":"timer clock","⏰":"alarm clock","⏳":"hourglass done","⌛":"hourglass","🔋":"battery","🪫":"low battery","🔌":"electric plug","🗑️":"wastebasket trash","🛒":"shopping cart",
  "🎁":"wrapped gift present","🎈":"balloon party","🎀":"ribbon bow","🎊":"confetti ball","🎉":"party popper celebration","🎎":"japanese doll","🎏":"carp streamer","🎐":"wind chime","🧧":"red envelope","📦":"package box",
  "📮":"mailbox","📫":"mailbox closed","📪":"mailbox closed","📬":"mailbox open","📭":"mailbox open empty","📧":"email envelope","📨":"incoming envelope","📩":"incoming envelope arrow","📤":"outbox tray",
  "⭐":"star glowing yellow","🌟":"glowing star","✨":"sparkles","💫":"dizzy star","⚡":"high voltage lightning","🌈":"rainbow","☀️":"sun sunny","🌤️":"sun behind cloud","⛅":"sun behind cloud","🌥️":"sun behind cloud","☁️":"cloud",
  "🌦️":"cloud rain","🌧️":"cloud rain","⛈️":"thunder cloud rain","🌩️":"thunder cloud","🌨️":"cloud snow","❄️":"snowflake snow","☃️":"snowman","⛄":"snowman without snow","🌬️":"wind face","💨":"dash wind",
  "💧":"droplet water","💦":"sweat droplets water","☔":"rain umbrella","☂️":"umbrella","🌊":"wave water","🌪️":"tornado","🔥":"fire flame hot","🌡️":"thermometer temperature",
  "🌙":"crescent moon","🌛":"first quarter moon","🌜":"last quarter moon","🌝":"full moon face","🌞":"sun face","🪐":"planet ringed","☄️":"comet",
  "♈":"aries zodiac","♉":"taurus zodiac","♊":"gemini zodiac","♋":"cancer zodiac","♌":"leo zodiac","♍":"virgo zodiac","♎":"libra zodiac","♏":"scorpius zodiac","♐":"sagittarius zodiac","♑":"capricorn zodiac",
  "♒":"aquarius zodiac","♓":"pisces zodiac","⛎":"ophiuchus zodiac",
  "🔀":"shuffle button","🔁":"repeat button","🔂":"repeat one","▶️":"play button","⏩":"fast forward","⏭️":"skip forward","⏯️":"play pause","◀️":"reverse button","⏪":"rewind","⏮️":"skip back",
  "🔼":"up button","⏫":"fast up","🔽":"down button","⏬":"fast down","⏸️":"pause button","⏹️":"stop button","⏺️":"record button","⏏️":"eject button","🎵":"musical note","🎶":"musical notes",
  "🔇":"muted speaker","🔈":"speaker low","🔉":"speaker medium","🔊":"speaker high","📢":"megaphone loudspeaker","📣":"cheering megaphone","📯":"postal horn","🔔":"bell ring","🔕":"bell no",
  "✅":"check mark done","☑️":"check mark ballot","✔️":"heavy check mark","❌":"cross mark no","❎":"cross mark button","➕":"plus sign add","➖":"minus sign subtract","➗":"division sign divide","✖️":"multiply sign times",
  "♾️":"infinity","💲":"dollar sign money","💱":"currency exchange","🔱":"trident emblem","📛":"name badge","🔰":"japanese novice","⭕":"heavy large circle","❓":"question mark","❔":"white question mark",
  "❗":"exclamation mark","❕":"white exclamation","🆚":"vs button","💮":"white flower","🉐":"circled ideograph advantage","㊙️":"circled ideograph secret","㊗️":"circled ideograph congratulation","🈴":"japanese here",
  "🏳️":"white flag","🏴":"black flag","🚩":"triangular flag","🎌":"crossed flags","🏁":"checkered flag","🏳️‍🌈":"rainbow flag","🏳️‍⚧️":"transgender flag","🏴‍☠️":"pirate flag",
};

// ─── Pre-built search list ──────────────────────────────────────────────────
// Normalise each emoji before keyword lookup so variation-selector mismatches
// don't silently produce empty strings.
export const ALL_EMOJIS = EMOJI_CATEGORIES.flatMap((cat) =>
  cat.emojis.map((e) => ({
    emoji: e,
    category: cat.name,
    keywords: (EMOJI_KEYWORDS[norm(e)] || cat.name).toLowerCase(),
  }))
);